intercept-console-error.ts:41 React has detected a change in the order of Hooks called by %s. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://react.dev/link/rules-of-hooks
   Previous render            Next render
   ------------------------------------------------------
%s   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AdminDashboardPage 1. useContext                 useContext
2. useContext                 useContext
3. useState                   useState
4. useState                   useState
5. useState                   useState
6. useEffect                  useEffect
7. useEffect                  useEffect
8. useMemo                    useMemo
9. useMemo                    useMemo
10. useMemo                   useMemo
11. useMemo                   useMemo
12. useMemo                   useMemo
13. useMemo                   useMemo
14. useMemo                   useMemo
15. useMemo                   useMemo
16. undefined                 useMemo

error @ intercept-console-error.ts:41Entenda o erro
error-boundary-callbacks.ts:101 Uncaught Error: Rendered more hooks than during the previous render.Entenda o erro
use-websocket.ts:16 WebSocket connection to 'wss://6000-firebase-studio-1748529743284.cluster-etsqrqvqyvd4erxx7qq32imrjk.cloudworkstations.dev/_next/webpack-hmr' failed:
(anônimo) @ use-websocket.ts:16Entenda o erro
Geist_Variable-s.p.f406b17f.woff2:1

           Failed to load resource: the server responded with a status of 403 ()Entenda o erro
GeistMono_Variable.p.6bae060c.woff2:1

           Failed to load resource: the server responded with a status of 403 ()Entenda o erro
GeistMono_Variable.p.6bae060c.woff2:1

           Failed to load resource: the server responded with a status of 403 ()Entenda o erro
Geist_Variable-s.p.f406b17f.woff2:1

           Failed to load resource: the server responded with a status of 403 ()Entenda o erro
AuthContext.tsx:78 User i4MDm9TOM8ckYJJCj7QWXZz6NXC3 is an admin.
intercept-console-error.ts:41 Error fetching total users: FirebaseError: Missing or insufficient permissions.